In [2]:
import torch

x = torch.tensor([5,3])
y = torch.tensor([2,4])

print(x*y)

tensor([10, 12])


In [6]:
x = torch.zeros([2,5])
print(x)
x.shape

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


torch.Size([2, 5])

In [8]:
y = torch.rand([2,5])
y

tensor([[0.0545, 0.3282, 0.9829, 0.7778, 0.9878],
        [0.5668, 0.4173, 0.9310, 0.8073, 0.3057]])

In [9]:
y = y.view(1,10)
y

tensor([[0.0545, 0.3282, 0.9829, 0.7778, 0.9878, 0.5668, 0.4173, 0.9310, 0.8073,
         0.3057]])